### ISSUE TITLE
Drum Kit

### ISSUE THREAD

**Issue by Surajvatsya** [rahulray11/github-fest-2021#53]
I'll make a drum kit which will produce as similar as the original one.  Either you will press the respected key written over the drum kit or click over the drum kit you want to hear sound from.
@rahulray11  Sir, Please assign me this issue.

![image](https://user-images.githubusercontent.com/68156079/135997503-c3e65be3-003e-4193-802e-cb0259c06d1f.png)

**Comment by rahulray11** [comment]
Ok you will start working on it. And after completion of your project give
a PR request.
